### ISSUE TITLE
ikuuu机场签到提示账号或密码错误

### ISSUE THREAD

**Issue by Mr-Coffee666** [Maotechh/AirportSign#2]
![image](https://user-images.githubusercontent.com/66343425/209892344-4ca7ae88-4b98-46cf-a241-de79152539f4.png)

之前一直用的好好的 ，最近就提示这个，望大佬回复下，谢谢！

**Comment by Maotechh** [comment]
ikuuu新加了登录Google CAPTCHA，正在研究能否绕过，如果不行只能获取cookie了

**Comment by Mr-Coffee666** [comment]
> ikuuu新加了登录Google CAPTCHA，正在研究能否绕过，如果不行只能获取cookie了

好的  谢谢大佬回复  顺便问一下咱有交流群吗？目前只进了tg通知群

**Comment by Maotechh** [comment]
暂时没有，准备等频道到300-500人规模的时候再建，现在即使建了人估计也很少

**Comment by Mr-Coffee666** [comment]
好的

**Comment by Maotechh** [comment]
我思考了一会，还是感觉得建，200多人了都，很多人不会去github提issue，还是搞个群聊问问题门槛低点
